/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdocoesIndexRouteImport } from './routes/adocoes/index'
import { Route as AdocoesIdRouteImport } from './routes/adocoes/$id'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdocoesIndexRoute = AdocoesIndexRouteImport.update({
  id: '/adocoes/',
  path: '/adocoes/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdocoesIdRoute = AdocoesIdRouteImport.update({
  id: '/adocoes/$id',
  path: '/adocoes/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/adocoes/$id': typeof AdocoesIdRoute
  '/adocoes/': typeof AdocoesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/adocoes/$id': typeof AdocoesIdRoute
  '/adocoes': typeof AdocoesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/adocoes/$id': typeof AdocoesIdRoute
  '/adocoes/': typeof AdocoesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/adocoes/$id' | '/adocoes/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/adocoes/$id' | '/adocoes'
  id: '__root__' | '/' | '/admin' | '/adocoes/$id' | '/adocoes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdocoesIdRoute: typeof AdocoesIdRoute
  AdocoesIndexRoute: typeof AdocoesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adocoes/': {
      id: '/adocoes/'
      path: '/adocoes'
      fullPath: '/adocoes/'
      preLoaderRoute: typeof AdocoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adocoes/$id': {
      id: '/adocoes/$id'
      path: '/adocoes/$id'
      fullPath: '/adocoes/$id'
      preLoaderRoute: typeof AdocoesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdocoesIdRoute: AdocoesIdRoute,
  AdocoesIndexRoute: AdocoesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
